#!/usr/bin/env python3
"""
Jarvis "thinking" chime generator — for the ESP32 voice box.

Synthesizes a soft three-note bell arpeggio (C5 → E5 → G5) with realistic
bell partials (higher harmonics decay faster, slight inharmonicity), then
writes:

  esp32/assets/jarvis-chime.wav  — 16 kHz, 16-bit, mono WAV
  esp32/assets/jarvis-chime.h    — PROGMEM int16_t array (zero-decode playback)

Usage:
  python3 esp32/tools/make_chime.py          # regenerate with default notes
  python3 esp32/tools/make_chime.py 660 792  # custom note frequencies

Everything below is tweakable; rerun and reflash to hear changes.
"""
import math
import os
import struct
import sys
import wave

SR = 16000          # sample rate — matches the ESP32 I2S mic pipeline
AMP = 0.55          # peak amplitude (0..1) — keep it gentle
ATTACK = 0.006      # seconds of fade-in per note (kills clicks)
SPACING = 0.24      # seconds between note starts
TAIL = 0.9          # decay tail after the last note

# Default note frequencies: a rising C-major arpeggio.
DEFAULT_NOTES = [523.25, 659.25, 783.99]   # C5 E5 G5

# Bell partials: (freq_multiplier, gain, decay_seconds)
# Higher partials die faster, like a struck bell.
PARTIALS = [
    (1.00, 1.00, 0.42),
    (2.76, 0.32, 0.26),
    (5.40, 0.10, 0.16),
]
# Slight inharmonicity — real bells are not exact integer multiples.
INHARMONIC = 0.002


def render(notes: list[float]) -> tuple[list[int], float]:
    total_s = notes[-1][1] + SPACING + TAIL
    total = int(total_s * SR)
    mix = [0.0] * total

    for freq, start in notes:
        for ratio, gain, decay in PARTIALS:
            f = freq * ratio * (1.0 + INHARMONIC * ratio)
            start_i = int(start * SR)
            for i in range(start_i, total):
                t = (i - start_i) / SR
                env = math.exp(-t / decay) * min(1.0, t / ATTACK)
                mix[i] += gain * env * math.sin(2.0 * math.pi * f * t)

    peak = max(abs(s) for s in mix) or 1.0
    samples = [int(max(-1.0, min(1.0, AMP * s / peak)) * 32767) for s in mix]
    rms = math.sqrt(sum((s / 32767.0) ** 2 for s in samples) / len(samples))
    return samples, rms


def write_wav(path: str, samples: list[int]) -> None:
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(struct.pack("<%dh" % len(samples), *samples))


def write_header(path: str, samples: list[int]) -> None:
    lines = ["// Auto-generated by esp32/tools/make_chime.py — do not edit by hand.",
             "#ifndef JARVIS_CHIME_H",
             "#define JARVIS_CHIME_H",
             "#include <stdint.h>",
             f"#define JARVIS_CHIME_SAMPLE_RATE {SR}",
             f"#define JARVIS_CHIME_NUM_SAMPLES {len(samples)}",
             "static const int16_t JARVIS_CHIME[] PROGMEM = {"]
    per_line = 12
    for i in range(0, len(samples), per_line):
        chunk = ", ".join(str(s) for s in samples[i:i + per_line])
        lines.append("  " + chunk + ",")
    lines += ["};", "#endif"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> None:
    freqs = [float(a) for a in sys.argv[1:]] or DEFAULT_NOTES
    # Start times: each note begins SPACING after the previous one.
    notes = [(f, i * SPACING) for i, f in enumerate(freqs)]

    samples, rms = render(notes)
    root = os.path.join(os.path.dirname(__file__), "..")
    assets = os.path.join(root, "assets")
    os.makedirs(assets, exist_ok=True)
    wav_path = os.path.join(assets, "jarvis-chime.wav")
    h_path = os.path.join(assets, "jarvis-chime.h")
    write_wav(wav_path, samples)
    write_header(h_path, samples)

    print(f"notes:        {' '.join(f'{f:.2f} Hz' for f in freqs)}")
    print(f"duration:     {len(samples) / SR:.2f}s  ({len(samples)} samples @ {SR} Hz)")
    print(f"peak:         {AMP:.2f}  rms: {rms:.3f} ({20 * math.log10(rms) + 3:.1f} dBFS-ish)")
    print(f"wav:          {wav_path} ({os.path.getsize(wav_path)} bytes)")
    print(f"header:       {h_path} ({os.path.getsize(h_path)} bytes)")


if __name__ == "__main__":
    main()
