import { Router } from "express";
import { promises as fs } from "node:fs";
import path from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { desc, eq } from "drizzle-orm";
import { buildApps, db } from "@workspace/db";
import {
  ensureWorkspace,
  getSessionCwd,
  getWorkspaceCommandEnvironment,
  getWorkspaceRoot,
  listWorkspaceFiles,
  readWorkspaceFile,
  writeWorkspaceFile,
  WORKSPACE_ROOT,
} from "../../lib/workspace";
import { getStorage, persistFile } from "../../lib/storage";
import { jarvisConfig } from "../../config/jarvis";
import { pooledClient } from "../../lib/llm-client";
import type { Browser, Page } from "puppeteer";

const puppeteerPromise = import("puppeteer");

const router = Router();
const previewProcesses = new Map<string, { child: ChildProcess; port: number; command: string; output: string }>();

function previewKey(workspaceId: string, sessionId: string): string {
  return `${workspaceId}:${sessionId}`;
}

/**
 * LLM-backed starter project generation. The model is asked to return a JSON
 * object mapping relative file paths to file contents. The response is parsed
 * leniently, and a deterministic single-page fallback is used when the model
 * is unavailable or returns something unparseable, so the studio always gets
 * a working starter.
 */
async function generateStarterFiles(
  prompt: string,
  answers: Record<string, string>,
  feedback: string | null,
  existingFiles: string[],
): Promise<Record<string, string>> {
  const userSummary = Object.entries(answers)
    .map(([question, answer]) => `${question}: ${answer}`)
    .join("\n");
  const existing = existingFiles.length > 0
    ? `\nExisting files in the workspace (keep and update them, do not duplicate):\n${existingFiles.join("\n")}`
    : "";
  const feedbackLine = feedback ? `\nThe user reviewed a preview and asked for these changes:\n${feedback}\n\nApply the changes and return the COMPLETE updated content of every file that changes (and any new files).` : "";

  const fallback = (): Record<string, string> => {
    const title = (prompt.split(/[\n.]/)[0] || "My App").trim().slice(0, 60) || "My App";
    const escaped = title.replace(/[<>&"]/g, (ch) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" })[ch] ?? ch);
    const html = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>${escaped}</title>\n<style>\n:root{color-scheme:dark}\n*{box-sizing:border-box}\nbody{margin:0;font-family:system-ui,-apple-system,sans-serif;background:radial-gradient(1200px 600px at 20% -10%,#1b2a4a,#0b1020 55%);color:#e8eefc;min-height:100vh;display:grid;place-items:center;padding:24px}\nmain{max-width:680px;width:100%;padding:48px;border:1px solid #34405f;border-radius:24px;background:rgba(21,29,51,.7);backdrop-filter:blur(8px)}\nh1{margin:0 0 8px;font-size:2rem;color:#8fb3ff}\np{line-height:1.7;color:#b9c5df;margin:8px 0 24px}\nbutton{background:#8fb3ff;color:#0b1020;border:0;border-radius:12px;padding:12px 20px;font-weight:600;cursor:pointer}\nbutton:hover{filter:brightness(1.1)}\n</style>\n</head>\n<body>\n<main>\n<h1>${escaped}</h1>\n<p>This starter was generated locally by Jarvis from your description. Open the editor to customize it, then run it in the Preview tab.</p>\n<p>Prompt: ${(prompt || "A simple app").replace(/[<>&"]/g, "")}</p>\n<button onclick="document.body.style.background='radial-gradient(1200px 600px at 80% 110%,#1b2a4a,#0b1020 55%)"">Toggle accent</button>\n</main>\n</body>\n</html>\n`;
    return { "index.html": html, "README.md": `# ${escaped}\n\nStarter generated by Jarvis.\n` };
  };

  try {
    const client = pooledClient();
    const completion = await client.chat.completions.create({
      model: jarvisConfig.llmModel,
      messages: [
        {
          role: "system",
          content:
            "You are the scaffolding engine inside a web-based IDE. The user wants a starter project built. " +
            "Return ONLY a valid JSON object where each key is a relative file path and each value is the complete file content. " +
            "No markdown fences, no explanation, no extra text before or after the JSON. " +
            "Build a single-page app with vanilla HTML, CSS and JavaScript (no external build step, it must run from a static server). " +
            "Make it visually polished, modern, and complete. Escape backslashes and quotes correctly inside the JSON string values. " +
            "Never use the em dash character anywhere in generated content.",
        },
        {
          role: "user",
          content:
            `The user wants: ${prompt}\n\nAnswers to the clarifying questions:\n${userSummary || "(none provided)"}\n${feedbackLine}\n${existing}`,
        },
      ],
      temperature: 0.6,
      max_tokens: 3000,
    });
    const raw = completion.choices[0]?.message?.content?.trim() ?? "";
    const match = raw.match(/\{[\s\S]*\}/);
    if (!match) return fallback();
    const parsed = JSON.parse(match[0]) as unknown;
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return fallback();
    const files: Record<string, string> = {};
    for (const [rel, content] of Object.entries(parsed as Record<string, unknown>)) {
      if (typeof rel !== "string" || !rel.trim() || rel.includes("\\")) continue;
      if (!/^[a-zA-Z0-9._/ -]+$/.test(rel) || rel.startsWith("/") || rel.includes("..")) continue;
      if (typeof content !== "string" || content.length > 200_000) continue;
      files[rel] = content;
    }
    return Object.keys(files).length > 0 ? files : fallback();
  } catch {
    return fallback();
  }
}

interface BuildReviewResult {
  done: boolean;
  summary: string;
  fixRequest: string | null;
  deferred: string[];
  filesChanged: string[];
}

function parseJsonObject(raw: string): Record<string, unknown> | null {
  const match = raw.match(/{[\s\S]*}/);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[0]) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? parsed as Record<string, unknown>
      : null;
  } catch {
    return null;
  }
}

function reviewFallback(prompt: string, files: string[], previewOutput: string): BuildReviewResult {
  const hasIndex = files.some((file) => file.toLowerCase() === "index.html");
  const hasRuntimeError = /\b(error|failed|exception|not found|cannot|syntaxerror)\b/i.test(previewOutput);
  if (!hasIndex) {
    return {
      done: false,
      summary: "The preview is missing an index.html entry point.",
      fixRequest: `Create a complete index.html entry point for this app: ${prompt}`,
      deferred: [],
      filesChanged: [],
    };
  }
  return {
    done: !hasRuntimeError,
    summary: hasRuntimeError
      ? "The preview log contains a runtime error that needs another fix pass."
      : "The workspace has an HTML entry point and no reported runtime errors.",
    fixRequest: hasRuntimeError ? `Inspect and fix the runtime issue shown in this preview output:\n${previewOutput.slice(-3000)}` : null,
    deferred: ["Accessibility and visual review should still be confirmed from the rendered preview."],
    filesChanged: [],
  };
}

async function reviewAndFixWorkspace(
  prompt: string,
  answers: Record<string, string>,
  workspaceId: string,
  previewOutput: string,
  passNumber: number,
): Promise<BuildReviewResult> {
  const entries = await listWorkspaceFiles(workspaceId);
  const files = entries
    .filter((entry) => entry.type === "file" && !/^\\.?env/i.test(entry.path))
    .map((entry) => entry.path)
    .slice(0, 120);
  const fallback = reviewFallback(prompt, files, previewOutput);
  try {
    const client = pooledClient();
    const completion = await client.chat.completions.create({
      model: jarvisConfig.llmModel,
      messages: [
        {
          role: "system",
          content:
            "You are the self-reviewer inside Jarvis Build Mode. Review a locally generated web app after it has been run. " +
            "Return ONLY JSON with this shape: {done:boolean,summary:string,fixRequest:string|null,deferred:string[]}. " +
            "Set done false only when a concrete runtime, structure, or obvious completeness issue can be fixed now. " +
            "Keep fixRequest short and actionable. Do not claim that a screenshot, accessibility, security, or performance check passed unless evidence is provided. " +
            "Never use the em dash character.",
        },
        {
          role: "user",
          content:
            `Prompt: ${prompt}\nAnswers: ${JSON.stringify(answers)}\nPass: ${passNumber} of 2\nFiles: ${files.join(", ") || "(none)"}\nPreview output:\n${previewOutput.slice(-6000)}`,
        },
      ],
      temperature: 0.1,
      max_tokens: 700,
    });
    const parsed = parseJsonObject(completion.choices[0]?.message?.content?.trim() ?? "");
    if (!parsed) return fallback;
    const done = parsed.done === true;
    const summary = cleanText(parsed.summary, 500) || fallback.summary;
    const fixRequest = done ? null : cleanText(parsed.fixRequest, 1800) || fallback.fixRequest;
    const deferred = Array.isArray(parsed.deferred)
      ? parsed.deferred.filter((item): item is string => typeof item === "string").map((item) => item.slice(0, 240)).slice(0, 8)
      : fallback.deferred;
    if (done || !fixRequest) return { done: true, summary, fixRequest: null, deferred, filesChanged: [] };

    const existingFiles = entries.filter((entry) => entry.type === "file").map((entry) => entry.path);
    const generated = await generateStarterFiles(prompt, answers, fixRequest, existingFiles);
    const filesChanged: string[] = [];
    for (const [relativePath, content] of Object.entries(generated)) {
      if (!safeWorkspacePath(relativePath, workspaceId)) continue;
      await writeWorkspaceFile(relativePath, content, workspaceId);
      filesChanged.push(relativePath);
    }
    return { done: false, summary, fixRequest, deferred, filesChanged };
  } catch {
    if (fallback.done || !fallback.fixRequest) return fallback;
    const existingFiles = entries.filter((entry) => entry.type === "file").map((entry) => entry.path);
    const generated = await generateStarterFiles(prompt, answers, fallback.fixRequest, existingFiles);
    const filesChanged: string[] = [];
    for (const [relativePath, content] of Object.entries(generated)) {
      if (!safeWorkspacePath(relativePath, workspaceId)) continue;
      await writeWorkspaceFile(relativePath, content, workspaceId);
      filesChanged.push(relativePath);
    }
    return { ...fallback, filesChanged };
  }
}

let screenshotBrowser: Browser | null = null;
let screenshotBrowserPromise: Promise<Browser> | null = null;

async function getScreenshotBrowser(): Promise<Browser> {
  if (screenshotBrowser && screenshotBrowser.connected) return screenshotBrowser;
  if (!screenshotBrowserPromise) {
    screenshotBrowserPromise = puppeteerPromise.then(async ({ default: puppeteer }) => {
      const executablePath = await puppeteer.executablePath();
      const browser = await puppeteer.launch({
        headless: true,
        executablePath,
        args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu", "--mute-audio", "--disable-dev-shm-usage"],
      });
      screenshotBrowser = browser;
      return browser;
    }).catch((err) => {
      screenshotBrowserPromise = null;
      throw err;
    });
  }
  return screenshotBrowserPromise;
}

/** Capture a PNG of the running preview and persist it to the Gallery store. */
async function capturePreviewPng(url: string, workspaceId: string): Promise<{ url: string; dataUrl: string } | null> {
  try {
    const browser = await getScreenshotBrowser();
    const page: Page = await browser.newPage();
    try {
      await page.setViewport({ width: 1280, height: 900, deviceScaleFactor: 1 });
      await page.goto(url, { waitUntil: "networkidle0", timeout: 20_000 });
      await new Promise((resolve) => setTimeout(resolve, 700));
      const shot = await page.screenshot({ type: "png" });
      const png = Buffer.from(shot);
      const stored = await persistFile({
        data: png,
        mimeType: "image/png",
        name: `build-preview-${workspaceId}.png`,
        kind: "image",
        owner: "user",
      });
      return {
        url: stored?.url ?? "",
        dataUrl: `data:image/png;base64,${png.toString("base64")}`,
      };
    } finally {
      await page.close();
    }
  } catch (err) {
    console.error("[build] screenshot failed:", err instanceof Error ? err.message : err);
    return null;
  }
}

/** Find the running preview entry for a workspace, if any. */
function findPreview(workspaceId: string, sessionId: string): { child: ChildProcess; port: number; command: string; output: string } | undefined {
  return previewProcesses.get(previewKey(workspaceId, sessionId));
}

/** Build a live preview URL for a workspace, or null when the workspace has no preview yet. */
function previewUrlFor(workspaceId: string, sessionId: string, port?: number | null): string | null {
  const preview = findPreview(workspaceId, sessionId);
  const p = port ?? preview?.port;
  if (!p || !Number.isInteger(p) || p < 1 || p > 65535) return null;
  return `http://127.0.0.1:${p}`;
}
const MAX_ENV_KEYS = 80;
const MAX_ENV_VALUE = 4000;

function cleanText(value: unknown, max: number): string {
  return typeof value === "string" ? value.trim().slice(0, max) : "";
}

function safeWorkspacePath(relPath: string, workspaceId = "default"): string | null {
  const root = getWorkspaceRoot(workspaceId);
  const target = path.resolve(root, relPath);
  return target.startsWith(`${root}${path.sep}`) ? target : null;
}

async function readWorkspaceEnv(workspaceId = "default"): Promise<Record<string, string>> {
  try {
    const content = await fs.readFile(path.join(getWorkspaceRoot(workspaceId), ".jarvis.env.json"), "utf8");
    const parsed = JSON.parse(content) as unknown;
    if (!parsed || typeof parsed !== "object") return {};
    return Object.fromEntries(Object.entries(parsed as Record<string, unknown>)
      .filter(([key, value]) => /^[A-Z][A-Z0-9_]{0,63}$/.test(key) && typeof value === "string")
      .slice(0, MAX_ENV_KEYS)
      .map(([key, value]) => [key, String(value).slice(0, MAX_ENV_VALUE)]));
  } catch {
    return {};
  }
}

async function writeWorkspaceEnv(env: Record<string, string>, workspaceId = "default"): Promise<void> {
  await ensureWorkspace(workspaceId);
  await fs.writeFile(path.join(getWorkspaceRoot(workspaceId), ".jarvis.env.json"), JSON.stringify(env, null, 2), "utf8");
}

function serializeSavedApp(row: typeof buildApps.$inferSelect) {
  return { ...row, metadata: row.metadata ?? {} };
}

router.get("/build/apps", async (req, res) => {
  try {
    const rows = await db.select().from(buildApps).orderBy(desc(buildApps.updatedAt));
    res.json(rows.map(serializeSavedApp));
  } catch (err) {
    req.log.error({ err }, "Failed to list build apps");
    res.status(500).json({ error: "Failed to list build apps" });
  }
});

router.post("/build/apps", async (req, res) => {
  const name = cleanText(req.body?.name, 100) || "Untitled build";
  const description = cleanText(req.body?.description, 500);
  const metadata = {
    runCommand: cleanText(req.body?.runCommand, 400),
    previewPort: Number.isInteger(req.body?.previewPort) ? req.body.previewPort : null,
    savedAt: new Date().toISOString(),
  };
  try {
    const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
    await ensureWorkspace(workspaceId);
    const filesSnapshot = await listWorkspaceFiles(workspaceId);
    const contents: Record<string, string> = {};
    for (const entry of filesSnapshot) {
      if (entry.type !== "file" || entry.path === ".jarvis.env.json") continue;
      const result = await readWorkspaceFile(entry.path, 200_000, workspaceId);
      if (result.ok) contents[entry.path] = result.content;
    }
    const env = await readWorkspaceEnv(workspaceId);
    const manifest = Buffer.from(JSON.stringify({ version: 1, files: contents, env }, null, 2), "utf8");
    const stored = await persistFile({
      data: manifest,
      mimeType: "application/json",
      name: `${name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.jarvis-build.json`,
      kind: "build-app",
      owner: "user",
    });
    if (!stored) {
      res.status(500).json({ error: "Could not persist the build snapshot" });
      return;
    }
    const [row] = await db.insert(buildApps).values({
      name,
      description,
      fileId: stored.fileId,
      metadata: { ...metadata, storageKey: stored.key, fileCount: Object.keys(contents).length, envKeys: Object.keys(env) },
    }).returning();
    res.status(201).json(serializeSavedApp(row));
  } catch (err) {
    req.log.error({ err }, "Failed to save build app");
    res.status(500).json({ error: "Failed to save build app" });
  }
});

router.post("/build/apps/:id/restore", async (req, res) => {
  try {
    const [app] = await db.select().from(buildApps).where(eq(buildApps.id, req.params.id));
    const metadata = (app?.metadata ?? {}) as { storageKey?: string };
    if (!app || !metadata.storageKey) {
      res.status(404).json({ error: "Saved build app not found" });
      return;
    }
    const blob = await getStorage().get(metadata.storageKey);
    if (!blob) {
      res.status(404).json({ error: "Saved build snapshot is unavailable" });
      return;
    }
    const snapshot = JSON.parse(blob.data.toString("utf8")) as { files?: Record<string, string>; env?: Record<string, string> };
    for (const [filePath, content] of Object.entries(snapshot.files ?? {})) {
      if (!safeWorkspacePath(filePath, cleanText(req.body?.workspaceId, 64) || "default")) continue;
      await writeWorkspaceFile(filePath, typeof content === "string" ? content : "", cleanText(req.body?.workspaceId, 64) || "default");
    }
    await writeWorkspaceEnv(snapshot.env ?? {}, cleanText(req.body?.workspaceId, 64) || "default");
    await db.update(buildApps).set({ updatedAt: new Date() }).where(eq(buildApps.id, app.id));
    res.json({ ok: true, restoredFiles: Object.keys(snapshot.files ?? {}).length });
  } catch (err) {
    req.log.error({ err }, "Failed to restore build app");
    res.status(500).json({ error: "Failed to restore build app" });
  }
});

router.get("/build/env", async (req, res) => {
  const workspaceId = cleanText(req.query.workspaceId, 64) || "default";
  res.json({ workspaceId, env: await readWorkspaceEnv(workspaceId) });
});

router.put("/build/env", async (req, res) => {
  const raw = req.body?.env;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    res.status(400).json({ error: "env must be an object" });
    return;
  }
  const env = Object.fromEntries(Object.entries(raw as Record<string, unknown>)
    .filter(([key, value]) => /^[A-Z][A-Z0-9_]{0,63}$/.test(key) && typeof value === "string")
    .slice(0, MAX_ENV_KEYS)
    .map(([key, value]) => [key, String(value).slice(0, MAX_ENV_VALUE)]));
  await writeWorkspaceEnv(env, cleanText(req.body?.workspaceId, 64) || "default");
  res.json({ env });
});

router.post("/build/ask", async (req, res) => {
  const prompt = cleanText(req.body?.prompt, 300).toLowerCase();
  const inventory = [
    { key: "interface", label: "Professional responsive interface", selected: true },
    { key: "runtime", label: "Local runnable preview", selected: true },
    { key: "accessibility", label: "Accessibility pass", selected: /accessib|a11y|keyboard|screen reader/.test(prompt) },
    { key: "data", label: "Local data or persistence", selected: /database|data|storage|save|persist|crud/.test(prompt) },
    { key: "auth", label: "Local authentication flow", selected: /auth|login|log in|sign up|account|password/.test(prompt) },
    { key: "ai", label: "AI interaction surface", selected: /\bai\b|assistant|chat|llm|model|generate/.test(prompt) },
    { key: "mobile", label: "Mobile responsive layout", selected: /mobile|responsive|phone|tablet/.test(prompt) },
  ];
  res.json({
    inventory,
    questions: [
      { key: "appType", label: "What kind of app is this?", options: ["Landing page", "Dashboard", "Portfolio", "Game", "Tool or utility"] },
      { key: "uiStyle", label: "What UI style do you prefer?", options: ["Dark and futuristic", "Clean and minimal", "Colorful and playful", "Glassmorphism", "Retro or vintage"] },
      { key: "aiProvider", label: "Will it talk to an AI provider?", options: ["No AI needed", "OpenAI-compatible API", "Simple local demo"] },
      { key: "scope", label: "How big should the first version be?", options: ["Single page", "Two or three sections", "Multi-page feel"] },
    ],
  });
});

router.post("/build/scaffold", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const prompt = cleanText(req.body?.prompt, 300) || "a simple Jarvis starter app";
  const rawAnswers = (req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers))
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers: Record<string, string> = {};
  for (const [key, value] of Object.entries(rawAnswers)) {
    const cleaned = cleanText(value, 200);
    if (key.length <= 100 && cleaned) answers[key] = cleaned;
  }
  const feedback = cleanText(req.body?.feedback, 2000) || null;
  try {
    await ensureWorkspace(workspaceId);
    const existingFiles = (await listWorkspaceFiles(workspaceId))
      .filter((entry) => entry.type === "file")
      .map((entry) => entry.path);
    const files = await generateStarterFiles(prompt, answers, feedback, existingFiles);
    for (const [relPath, content] of Object.entries(files)) {
      if (!safeWorkspacePath(relPath, workspaceId)) continue;
      await writeWorkspaceFile(relPath, content, workspaceId);
    }
    res.status(201).json({ ok: true, files: Object.keys(files), runtime: "static", previewCommand: "python3 -m http.server ${PORT}" });
  } catch (err) {
    req.log.error({ err }, "Failed to scaffold starter");
    res.status(500).json({ error: "Could not scaffold starter" });
  }
});

router.post("/build/iterate", async (req, res) => {
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const prompt = cleanText(req.body?.prompt, 300) || "a simple Jarvis starter app";
  const previewOutput = cleanText(req.body?.previewOutput, 6000);
  const passNumber = Math.min(2, Math.max(1, Number(req.body?.passNumber) || 1));
  const rawAnswers = req.body?.answers && typeof req.body.answers === "object" && !Array.isArray(req.body.answers)
    ? req.body.answers as Record<string, unknown>
    : {};
  const answers = Object.fromEntries(Object.entries(rawAnswers)
    .map(([key, value]) => [key, cleanText(value, 200)])
    .filter(([, value]) => value));
  try {
    await ensureWorkspace(workspaceId);
    const result = await reviewAndFixWorkspace(prompt, answers, workspaceId, previewOutput, passNumber);
    res.json({ ok: true, passNumber, ...result });
  } catch (err) {
    req.log.error({ err }, "Build self-review failed");
    res.status(500).json({ error: "Build self-review failed" });
  }
});

router.post("/build/screenshot", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "studio-preview";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const requestedUrl = cleanText(req.body?.url, 500);
  const url = requestedUrl && /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/|$)/i.test(requestedUrl)
    ? requestedUrl
    : previewUrlFor(workspaceId, sessionId, Number.isInteger(req.body?.port) ? Number(req.body.port) : null);
  if (!url) {
    res.status(400).json({ error: "No preview is running for this workspace" });
    return;
  }
  const shot = await capturePreviewPng(url, workspaceId);
  if (!shot) {
    res.status(500).json({ error: "Screenshot failed, the headless browser is unavailable" });
    return;
  }
  res.json({ ok: true, url: shot.url, dataUrl: shot.dataUrl });
});

router.post("/build/preview/start", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "default";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const command = cleanText(req.body?.command, 500);
  const port = Number(req.body?.port);
  if (!command || !Number.isInteger(port) || port < 1024 || port > 65535) {
    res.status(400).json({ error: "A command and valid preview port (1024-65535) are required" });
    return;
  }
  await ensureWorkspace(workspaceId);
  const key = previewKey(workspaceId, sessionId);
  const previous = previewProcesses.get(key);
  previous?.child.kill("SIGTERM");
  const env = await readWorkspaceEnv(workspaceId);
  const child = spawn("/bin/bash", ["-lc", command], {
    cwd: getSessionCwd(sessionId, workspaceId),
    env: getWorkspaceCommandEnvironment({ ...env, PORT: String(port), HOST: "0.0.0.0" }),
    detached: false,
    stdio: ["ignore", "pipe", "pipe"],
  });
  const entry = { child, port, command, output: "" };
  previewProcesses.set(key, entry);
  const collect = (chunk: Buffer) => { entry.output = `${entry.output}${chunk.toString()}`.slice(-12000); };
  child.stdout?.on("data", collect);
  child.stderr?.on("data", collect);
  child.on("exit", () => { if (previewProcesses.get(key)?.child === child) previewProcesses.delete(key); });
  res.status(201).json({ sessionId, workspaceId, port, url: `http://localhost:${port}`, running: true });
});

router.post("/build/preview/stop", async (req, res) => {
  const sessionId = cleanText(req.body?.sessionId, 100) || "default";
  const workspaceId = cleanText(req.body?.workspaceId, 64) || "default";
  const entry = previewProcesses.get(previewKey(workspaceId, sessionId));
  if (entry) {
    entry.child.kill("SIGTERM");
    previewProcesses.delete(previewKey(workspaceId, sessionId));
  }
  res.json({ ok: true });
});

router.get("/build/preview/status", async (req, res) => {
  const sessionId = cleanText(req.query.sessionId, 100) || "default";
  const workspaceId = cleanText(req.query.workspaceId, 64) || "default";
  const entry = previewProcesses.get(previewKey(workspaceId, sessionId));
  res.json(entry ? { running: true, workspaceId, port: entry.port, command: entry.command, output: entry.output.slice(-4000) } : { running: false, workspaceId });
});

export default router;
