import { Router } from "express";
import transcribeRouter from "./transcribe";
import chatRouter from "./chat";
import speakRouter from "./speak";
import conversationsRouter from "./conversations";
import settingsRouter from "./settings";
import memoriesRouter from "./memories";
import gmailRouter from "./gmail";
import spotifyRouter from "./spotify";
import browseRouter from "./browse";
import generateImageRouter from "./generate-image";
import codeRouter from "./code";
import researchRouter from "./research";
import pushRouter from "./push";
import llmKeysRouter from "./llm-keys";
import terminalRouter from "./terminal";
import verifyRouter from "./verify";
import secretsRouter from "./secrets";
import timersRouter from "./timers";
import projectsRouter from "./projects";
import groupsRouter from "./groups";
import buildRouter from "./build";
import hotReloadRouter from "./hot-reload";
import packageManagerRouter from "./package-manager";

const router = Router();

router.use(conversationsRouter);
router.use(settingsRouter);
router.use(memoriesRouter);
router.use(transcribeRouter);
router.use(chatRouter);
router.use(speakRouter);
router.use(gmailRouter);
router.use(spotifyRouter);
router.use("/browse", browseRouter);
router.use(generateImageRouter);
router.use(codeRouter);
router.use(researchRouter);
router.use(pushRouter);
router.use(llmKeysRouter);
router.use(secretsRouter);
router.use(terminalRouter);
router.use(verifyRouter);
router.use(timersRouter);
router.use(projectsRouter);
router.use(groupsRouter);
router.use(buildRouter);
router.use(hotReloadRouter);
router.use(packageManagerRouter);

export default router;
